### ISSUE TITLE
禁止fork，不认识字吗？

### ISSUE THREAD

**Issue by ghost** [tanggaohu/Nodi-privati#1]
RT

**Comment by tanggaohu** [comment]
不好意思，也许说出来你不信，但是实话实说我自己都不知道怎么fork了，我刚刚看见邮箱你发来的信息才知道的，而且居然fork了2次，我现在都删除了，感谢墨鱼大佬一直一来的分享。以后绝不乱点了，绝无下次！再次说声抱歉！
